### ISSUE TITLE
Run and insert the .py file for model (ML)

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/project_Ace#1]
As this model is made complete, the contributors are requested to run the code and submit the file in .ipynb with code being debugged.

Be sure to be assigned before contributing

**Comment by RishabhDevbanshi** [comment]
I would like to work on it.

**Comment by shivamsouravjha** [comment]
Assigned it @RishabhDevbanshi

**Comment by heythere12** [comment]
Hey, can I enhance the accuracy of the model ? :)

**Comment by shivamsouravjha** [comment]
@heythere12 after your work on the last repo no doubts you can! assigned it to you!
Being honest this Is a very small dataset of a Codeacademy capstone project and was an introductory project in ML. 
[CSV at ](https://discuss.codecademy.com/t/tennis-ace-challenge-project-python/462381)
You will have to download and use it accordingly.

**Comment by heythere12** [comment]
Hey @shivamsouravjha  I can not find tennis.csv file. Can you please help me with that?

**Comment by shivamsouravjha** [comment]
@heythere12 sorry for the wrong link in above try this [link](https://discuss.codecademy.com/t/tennis-ace-challenge-project-python/462381) , click on the solutions that would download two files, ignore the former and use the later CSV.

**Comment by heythere12** [comment]
Hey @shivamsouravjha, can you please check my PR and also it is showing invalid in the Hactoberfest. Can you please label it appropriately?

Thanks
Nishi

**Comment by shivamsouravjha** [comment]
@heythere12 I just did few changes(adding hacktoberfest labels and etc) please check and reply if it works or not in Hacktober.

Thanks and Regards 
Shivam

**Comment by heythere12** [comment]
Yes it works. Thanks a lot :) @shivamsouravjha 

Thanks
Nishi
